export default [
  "kills",
  "actions_per_min",
  "assists",
  "comeback",
  "courier_kills",
  "deaths",
  "denies",
  "duration",
  "lane_efficiency_pct",
  "purchase_gem",
  "gold_per_min",
  "hero_damage",
  "hero_healing",
  "kda",
  "last_hits",
  "level",
  "loss",
  "pings",
  "neutral_kills",
  "purchase_ward_observer",
  "purchase_rapier",
  "purchase_ward_sentry",
  "stomp",
  "stuns",
  "throw",
  "tower_damage",
  "tower_kills",
  "purchase_tpscroll",
  "win_rate",
  "xp_per_min",
];

// Records only for now. The histograms endpoint buckets with an integer width,
// so kills_per_min, whose whole range is under 1, would collapse into a single
// bar. Serving these there needs fractional bucket sizes, left for a follow-up.
export const perMinColumns = [
  "kills_per_min",
  "hero_damage_per_min",
  "tower_damage_per_min",
];
